### ISSUE TITLE
Reduce writes to JSON store

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js#1255]
> is it possible to disable storing [node].values.jsonl on disk? Constant disk writes add wear to storage for embedded devices...

Ref: https://github.com/zwave-js/zwavejs2mqtt/issues/115#issuecomment-751955662

**Comment by AlCalzone** [comment]
Disabling the storage makes no sense because after a restart or crash all interviews would need to be repeated completely.

I can do you one better though... The value store is based on `jsonl-db`, which has options to throttle the FS access:
https://github.com/AlCalzone/jsonl-db#controlling-file-system-access

We could expose a part of those options (or create presets): https://github.com/zwave-js/node-zwave-js/blob/fa4faff39fd49b50702f0f859a2e4206ec67c334/packages/zwave-js/src/lib/driver/Driver.ts#L720-L733

**Comment by robertsLando** [comment]
> We could expose a part of those options (or create presets):

I think this would be a good addon to driver options :)

**Comment by AlCalzone** [comment]
Since we're still working on 6.x, lets merge the `fs`, `cacheDir` and these new options into a new object-type property. Now's the time for housekeeping.

**Comment by AlCalzone** [comment]
And I prefer presets in order to not overload the options with stuff users can mess up. E.g. `persistence: "tight" | "default" | "loose"` for frequent/normal/unfrequent fs access (names up for discussion).

**Comment by robertsLando** [comment]
> And I prefer presets in order to not overload the options with stuff users can mess up

I'm +1 for this! 

> lets merge the fs, cacheDir and these new options into a new object-type property

Yep, we could wrap all them in a `storage` property of driver options?
