### ISSUE TITLE
Config: Add check for duplicate parameters

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1794]

**Comment by AlCalzone** [comment]
@blhoward2 We can't do this - at least not easily.
https://github.com/json5/json5/pull/217

One other way would be to use the JSON schema to validate the files, but that won't pick up duplicate keys in templates.

**Comment by blhoward2** [comment]
Why not just build a Set of the parameter numbers since they have to be unqiue, then compare the size to the number of parameters? If it is less there is a duplicate value somewhere? That wouldn't identify which is the duplicate but you could at least display an error message and fail. If you want to display which then just loop back through the set deleting values and display an error where the parameter doesn't exist on the second encounter.

**Comment by AlCalzone** [comment]
The thing is, after `JSON5.parse` we don't see the duplicate. I could change it so the comments get stripped and the file parsed with the built-in JSON class, which would throw on duplicates.

**Comment by blhoward2** [comment]
Ah, yeah I was thinking about after it's already in memory. I'm not sure it's a huge deal. Stripping the comments sounds annoying since they aren't just at the top in some files.

**Comment by AlCalzone** [comment]
Should be easy enough to do with a regex 🤷🏻‍♂️

**Comment by blhoward2** [comment]
I wouldn't worry about it. I can just not make mistakes, lol. Hopefully the templating would cut down on it too.
