### ISSUE TITLE
popp electric strike lock 012501 fw 1.5

### ISSUE THREAD

**Issue by hubik77** [zwave-js/zwave-js#2138]
Hi

![Zrzut ekranu 2021-03-23 o 17 48 40](https://user-images.githubusercontent.com/57366861/112185022-1b400080-8c00-11eb-9a1b-d26b0af8ccd2.png)

The lock does not work properly in this firmware version, not all entities are active.

**Comment by marcus-j-davies** [comment]
Hi,

If you're reporting an issue about the device not working (due to its firmware) - speak to the manufacturer.
if you need help from us, start by filling in the template, providing everything we need to help.

![image](https://user-images.githubusercontent.com/55892693/112188150-a7e7c000-8bfa-11eb-9711-ff71e34b2ae3.png)

**Comment by AlCalzone** [comment]
This 👆🏻

We can't act on issues without sufficient info.
