### ISSUE TITLE
Inovelli LZW36 Light turns on when Fan commanded on

### ISSUE THREAD

**Issue by kreene1987** [zwave-js/zwave-js#2480]
Since updating to 0.1.20, when my LZW Fan is commanded on, the light is also turning on. Here are the debug logs.

[LZW36FanOnLightOn.txt](https://github.com/zwave-js/node-zwave-js/files/6393529/LZW36FanOnLightOn.txt)

Probably related to #2159 and/or #2154.

**Comment by kreene1987** [comment]
I'll get way better logs, these are useless...

**Comment by blhoward2** [comment]
Don't worry about it, we know the issue we just missed readding a compat flag here as we work around it. I've pushed a PR fixing this for now.

**Comment by blhoward2** [comment]
Actually, if memory serves this one acts a bit differently. Try removing the controller from associations group 1 (the lifeline) and re-adding it. OZW setup weird associations sometimes and it breaks this one.

This flag is going to cause a third entity to be created, which will be on if any of the two are on. Just disable it in HA.

@AlCalzone I think we should still add the compat flag until you fix #2257

**Comment by kreene1987** [comment]
Can this be done from within ZJS, ZJS2M, or HA integration?

**Comment by blhoward2** [comment]
Can what be done? Removing the association? That can be done within zjs2mqtt but not otherwise right now. 

The temporary fix will roll out once merged in the next release. In the interim if you can get access to the device files inside the container you can change it on your end. How difficult that is depends on how you're running it and your level of familiarity. 

My point about disabling the new entity is just that it's going to create a third one for now that you don't care about.

**Comment by kreene1987** [comment]
Sorry I wasn't clear. I was speaking to this:

> Try removing the controller from associations group 1 (the lifeline) and re-adding it

If ZJS2M can do it I can make it happen. No issues on the additional entity, I can handle that!

**Comment by blhoward2** [comment]
Ah, yes. Go to the node in zjs2mqtt. Then go to the groups tab.
